#Requires -Version 5.1
<#
.SYNOPSIS
  Post-install: create a user-local Python venv with PaddleOCR for EnPu.

.DESCRIPTION
  Installs to: %LOCALAPPDATA%\EnPu\venv
  Launcher:    %LOCALAPPDATA%\EnPu\start-enpu-core-paddle.cmd

  EnPu desktop prefers this launcher when present (real OCR); otherwise uses
  the bundled mock enpu-core.exe sidecar.

  Safe to re-run. Does not require admin.
#>
[CmdletBinding()]
param(
  [switch]$Quiet
)

$ErrorActionPreference = "Stop"
$EnPuHome = Join-Path $env:LOCALAPPDATA "EnPu"
$Venv = Join-Path $EnPuHome "venv"
$Log = Join-Path $EnPuHome "install-paddle-ocr.log"
$Launcher = Join-Path $EnPuHome "start-enpu-core-paddle.cmd"
$CoreSrcHint = $PSScriptRoot  # resources next to install when run from INSTDIR

function Write-Log([string]$Msg) {
  $line = "[{0}] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Msg
  Add-Content -Path $Log -Value $line -Encoding UTF8
  if (-not $Quiet) { Write-Host $line }
}

New-Item -ItemType Directory -Force -Path $EnPuHome | Out-Null
Write-Log "=== EnPu PaddleOCR install start ==="
Write-Log "EnPuHome=$EnPuHome"

# Locate python
$py = $null
foreach ($c in @(
    (Get-Command python -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source),
    (Get-Command py -ErrorAction SilentlyContinue | Select-Object -ExpandProperty Source),
    "$env:LOCALAPPDATA\Programs\Python\Python312\python.exe",
    "$env:LOCALAPPDATA\Programs\Python\Python311\python.exe",
    "C:\Python312\python.exe",
    "C:\Python311\python.exe"
  )) {
  if ($c -and (Test-Path $c)) { $py = $c; break }
}

if (-not $py) {
  Write-Log "ERROR: Python 3.10+ not found on PATH."
  Write-Log "Install Python from https://www.python.org/downloads/ (check 'Add to PATH'), then re-run:"
  Write-Log "  powershell -ExecutionPolicy Bypass -File `"$PSCommandPath`""
  if (-not $Quiet) {
    try {
      Add-Type -AssemblyName System.Windows.Forms -ErrorAction SilentlyContinue
      [System.Windows.Forms.MessageBox]::Show(
        "未找到 Python。请先安装 Python 3.10+ 并勾选 Add to PATH，然后重新运行：`n$PSCommandPath`n`n日志: $Log",
        "EnPu · PaddleOCR 安装",
        "OK",
        "Warning"
      ) | Out-Null
    } catch {
      Write-Host "未找到 Python。请安装 Python 3.10+ 后重跑: $PSCommandPath"
    }
  }
  exit 1
}

Write-Log "Python=$py"
& $py --version 2>&1 | ForEach-Object { Write-Log $_ }

# Create venv
if (-not (Test-Path (Join-Path $Venv "Scripts\python.exe"))) {
  Write-Log "Creating venv at $Venv ..."
  & $py -m venv $Venv
} else {
  Write-Log "venv already exists: $Venv"
}

$pip = Join-Path $Venv "Scripts\pip.exe"
$vpy = Join-Path $Venv "Scripts\python.exe"
if (-not (Test-Path $pip)) { throw "venv pip missing: $pip" }

Write-Log "Upgrading pip..."
& $vpy -m pip install -U pip setuptools wheel 2>&1 | ForEach-Object { Write-Log $_ }

# Lightweight core API deps (no full monorepo) + paddle
# Note: paddle wheels are large; network required.
Write-Log "Installing FastAPI stack + OpenCV + PaddleOCR (this may take several minutes)..."
& $pip install `
  "fastapi>=0.110,<1" `
  "uvicorn[standard]>=0.27,<1" `
  "python-multipart>=0.0.9" `
  "pydantic>=2.0,<3" `
  "pydantic-settings>=2.0,<3" `
  "Pillow>=10.0,<12" `
  "numpy>=1.24,<3" `
  "opencv-python-headless>=4.8,<5" `
  "music21>=9.1,<10" `
  2>&1 | ForEach-Object { Write-Log $_ }

Write-Log "Installing paddlepaddle + paddleocr..."
& $pip install "paddlepaddle>=2.6.0,<3.1" "paddleocr>=2.7,<3" 2>&1 | ForEach-Object { Write-Log $_ }

# Optionally copy EnPu core app sources if shipped next to this script
$shippedCore = Join-Path $PSScriptRoot "enpu-core-src"
$appTarget = Join-Path $EnPuHome "core-app"
if (Test-Path (Join-Path $shippedCore "app")) {
  Write-Log "Copying shipped core sources → $appTarget"
  if (Test-Path $appTarget) { Remove-Item -Recurse -Force $appTarget }
  Copy-Item -Recurse -Force $shippedCore $appTarget
} elseif (Test-Path (Join-Path $PSScriptRoot "..\..\..\core\app")) {
  # Dev layout when script run from repo
  $repoCore = (Resolve-Path (Join-Path $PSScriptRoot "..\..\..\core")).Path
  Write-Log "Copying repo core → $appTarget"
  New-Item -ItemType Directory -Force -Path $appTarget | Out-Null
  Copy-Item -Recurse -Force (Join-Path $repoCore "app") (Join-Path $appTarget "app")
  Copy-Item -Force (Join-Path $repoCore "run_server.py") (Join-Path $appTarget "run_server.py") -ErrorAction SilentlyContinue
}

# Write launcher — prefer full core if present, else remind user
$launcherBody = @"
@echo off
REM EnPu PaddleOCR core launcher (generated by install-paddle-ocr.ps1)
setlocal
set ENPU_RECOGNIZE_ENGINE=paddleocr
set ENPU_HOST=127.0.0.1
set ENPU_PORT=8765
set ENPU_CORE_PORT=8765
set "VENV_PY=%LOCALAPPDATA%\EnPu\venv\Scripts\python.exe"
set "CORE_DIR=%LOCALAPPDATA%\EnPu\core-app"
if not exist "%VENV_PY%" (
  echo [enpu] venv python missing. Re-run install-paddle-ocr.ps1
  exit /b 1
)
if exist "%CORE_DIR%\run_server.py" (
  cd /d "%CORE_DIR%"
  "%VENV_PY%" run_server.py --engine paddleocr --host 127.0.0.1 --port 8765
  exit /b %ERRORLEVEL%
)
if exist "%CORE_DIR%\app\main.py" (
  cd /d "%CORE_DIR%"
  "%VENV_PY%" -m uvicorn app.main:app --host 127.0.0.1 --port 8765
  exit /b %ERRORLEVEL%
)
echo [enpu] core app sources not found under %CORE_DIR%
echo [enpu] Copy core/app + run_server.py there, or re-run installer with resources.
exit /b 2
"@
Set-Content -Path $Launcher -Value $launcherBody -Encoding ASCII
Write-Log "Wrote launcher: $Launcher"

# Marker for desktop to detect paddle readiness
$marker = Join-Path $EnPuHome "paddle-ready.json"
@{
  ok           = $true
  engine       = "paddleocr"
  venv         = $Venv
  launcher     = $Launcher
  installed_at = (Get-Date).ToString("o")
  python       = $py
} | ConvertTo-Json | Set-Content -Path $marker -Encoding UTF8

Write-Log "=== Done. First OCR run will download Paddle models (needs network). ==="
Write-Log "Launcher: $Launcher"
Write-Log "Log: $Log"

if (-not $Quiet) {
  try {
    Add-Type -AssemblyName System.Windows.Forms -ErrorAction SilentlyContinue
    [System.Windows.Forms.MessageBox]::Show(
      "PaddleOCR 环境已安装到:`n$Venv`n`n启动器:`n$Launcher`n`n重启 EnPu 后将优先使用真实 OCR（首次识别会下载模型）。`n日志: $Log",
      "EnPu · PaddleOCR 安装完成",
      "OK",
      "Information"
    ) | Out-Null
  } catch {}
}

exit 0
